title = "GCP Open Guide"
baseURL = "https://og-gcp.firebaseapp.com/"
theme = "og-gcp-theme"

[params]
	# Date format (refer to Go's date format)
	# Examples, "Mon, Jan 2, 2006" or "2006-01--2"
	date_format = "2006-01-02"
	longTitle = "Google Cloud Platform Open Guide"
	github = "github.com/cobookman/og-gcp"
	CSE = "012619341396918924035:q6lvujjnodu"

[params.logo]
	src = "images/logo.png"
	width = "209px"
	height = "209px"

[taxonomies]
	category = "categories"

[[menu.main]]
	name = "Compute"
	weight = -110
	identifier = "compute"
	url = "categories/compute/"

[[menu.main]]
	name = "Storage and Databases"
	weight = -100
	identifier = "storage_and_databases"
	url = "categories/storage_and_databases/"

[[menu.main]]
	name = "Machine Learning"
	weight = -90
	identifier = "machine-learning"
	url = "categories/machine-learning/"

[[menu.main]]
	name = "Administration"
	weight = -80
	identifier = "administration"
	url = "categories/administration/"
